all:
	true
install:
	mkdir -p $(DESTDIR)/usr/share/gnome-shell/extensions/please_log_out@bacchus.snucse.org
	cp metadata.json extension.js $(DESTDIR)/usr/share/gnome-shell/extensions/please_log_out@bacchus.snucse.org
